name: CloudFormation Validation

on:
  push:
    branches: ["main", "develop"]
    paths:
      - "templates/**.yaml"
      - "parameters/**.json"
      - ".github/workflows/cfn-lint.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "templates/**.yaml"
      - "parameters/**.json"

permissions:
  contents: read
  pull-requests: write   # Allows the workflow to post lint results as PR comments

jobs:
  # ─── JOB 1: CFN-LINT ────────────────────────────────────────────────────────
  cfn-lint:
    name: cfn-lint (Syntax & Best Practices)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install cfn-lint
        run: pip install cfn-lint

      - name: Run cfn-lint on all templates
        id: cfn-lint
        run: |
          echo "## cfn-lint Results" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

          # Lint all templates and capture output; exit non-zero on errors
          cfn-lint templates/*.yaml \
            --format pretty \
            --include-checks I \
            2>&1 | tee -a $GITHUB_STEP_SUMMARY

          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Upload cfn-lint results
        if: always()
        run: |
          cfn-lint templates/*.yaml --format json > cfn-lint-results.json 2>&1 || true

      - name: Upload lint artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cfn-lint-results
          path: cfn-lint-results.json
          retention-days: 14

  # ─── JOB 2: CFN-NAG (SECURITY SCAN) ────────────────────────────────────────
  cfn-nag:
    name: cfn-nag (Security Scanning)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"

      - name: Install cfn-nag
        run: gem install cfn-nag

      - name: Run cfn-nag on all templates
        id: cfn-nag
        run: |
          echo "## cfn-nag Security Scan Results" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

          # Run against all templates; suppress known acceptable warnings with --deny-list-path if needed
          cfn_nag_scan \
            --input-path templates/ \
            --template-pattern '.*\.yaml$' \
            --output-format txt \
            2>&1 | tee -a $GITHUB_STEP_SUMMARY

          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Upload cfn-nag results artifact
        if: always()
        run: |
          cfn_nag_scan \
            --input-path templates/ \
            --template-pattern '.*\.yaml$' \
            --output-format json > cfn-nag-results.json 2>&1 || true

      - name: Upload nag artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cfn-nag-results
          path: cfn-nag-results.json
          retention-days: 14

  # ─── JOB 3: VALIDATE JSON PARAMETERS ────────────────────────────────────────
  validate-parameters:
    name: Validate Parameter Files (JSON)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate all parameter JSON files
        run: |
          echo "## Parameter File Validation" >> $GITHUB_STEP_SUMMARY
          FAILED=0

          for f in parameters/*.json; do
            if jq empty "$f" 2>/dev/null; then
              echo "✅ $f" >> $GITHUB_STEP_SUMMARY
            else
              echo "❌ $f — invalid JSON" >> $GITHUB_STEP_SUMMARY
              FAILED=1
            fi
          done

          exit $FAILED

  # ─── JOB 4: SUMMARY STATUS CHECK ────────────────────────────────────────────
  # This job acts as a single required status check you can enforce via branch protection.
  ci-status:
    name: CI Status Gate
    runs-on: ubuntu-latest
    needs: [cfn-lint, cfn-nag, validate-parameters]
    if: always()

    steps:
      - name: Check all jobs passed
        run: |
          if [[ "${{ needs.cfn-lint.result }}" != "success" || \
                "${{ needs.cfn-nag.result }}"  != "success" || \
                "${{ needs.validate-parameters.result }}" != "success" ]]; then
            echo "One or more validation jobs failed."
            exit 1
          fi
          echo "All CloudFormation validation checks passed ✅"
