AWSTemplateFormatVersion: "2010-09-09"
Description: >
  AWS Landing Zone - IAM & Identity Center (SSO) Layer
  Provisions permission sets and group assignments for centralized access
  management across a multi-account AWS Organization.
  NOTE: IAM Identity Center must be enabled manually in the management account
  before deploying this stack. The IdentityStoreId and InstanceArn are required.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Identity Center Configuration"
        Parameters:
          - EnvironmentName
          - SSOInstanceArn
          - IdentityStoreId
          - ManagementAccountId
          - LogArchiveAccountId
          - SecurityToolingAccountId
      - Label:
          default: "Session Settings"
        Parameters:
          - AdminSessionDuration
          - ReadOnlySessionDuration

Parameters:
  EnvironmentName:
    Type: String
    Default: landing-zone
    Description: Prefix used for resource naming.

  SSOInstanceArn:
    Type: String
    Description: >
      ARN of the IAM Identity Center instance.
      Found in IAM Identity Center > Settings > ARN.
    AllowedPattern: "^arn:aws:sso:::instance/ssoins-[a-zA-Z0-9]+$"

  IdentityStoreId:
    Type: String
    Description: >
      Identity Store ID associated with the IAM Identity Center instance.
      Found in IAM Identity Center > Settings > Identity source.
    AllowedPattern: "^d-[a-zA-Z0-9]+$"

  ManagementAccountId:
    Type: String
    Description: AWS Account ID for the Management (root) account.
    AllowedPattern: "^[0-9]{12}$"

  LogArchiveAccountId:
    Type: String
    Description: AWS Account ID for the Log Archive account.
    AllowedPattern: "^[0-9]{12}$"

  SecurityToolingAccountId:
    Type: String
    Description: AWS Account ID for the Security Tooling account.
    AllowedPattern: "^[0-9]{12}$"

  AdminSessionDuration:
    Type: String
    Default: "PT4H"
    Description: ISO-8601 session duration for admin permission sets (e.g. PT4H = 4 hours).
    AllowedValues:
      - "PT1H"
      - "PT2H"
      - "PT4H"
      - "PT8H"

  ReadOnlySessionDuration:
    Type: String
    Default: "PT8H"
    Description: ISO-8601 session duration for read-only permission sets.
    AllowedValues:
      - "PT4H"
      - "PT8H"
      - "PT12H"

Resources:
  # ─── PERMISSION SETS ──────────────────────────────────────────────────────

  # Full administrator access - tightly scoped session
  AdministratorAccessPermissionSet:
    Type: AWS::SSO::PermissionSet
    Properties:
      Name: AdministratorAccess
      Description: Full administrator access. Restricted session duration.
      InstanceArn: !Ref SSOInstanceArn
      ManagedPolicies:
        - arn:aws:iam::aws:policy/AdministratorAccess
      SessionDuration: !Ref AdminSessionDuration
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: ManagedBy
          Value: CloudFormation

  # Read-only access for auditors and developers
  ReadOnlyAccessPermissionSet:
    Type: AWS::SSO::PermissionSet
    Properties:
      Name: ReadOnlyAccess
      Description: Read-only access across all services.
      InstanceArn: !Ref SSOInstanceArn
      ManagedPolicies:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      SessionDuration: !Ref ReadOnlySessionDuration
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: ManagedBy
          Value: CloudFormation

  # Security-focused access for the Security Tooling account
  SecurityAuditPermissionSet:
    Type: AWS::SSO::PermissionSet
    Properties:
      Name: SecurityAudit
      Description: >
        Security audit access with permissions for GuardDuty, SecurityHub,
        Config, CloudTrail, and related services.
      InstanceArn: !Ref SSOInstanceArn
      ManagedPolicies:
        - arn:aws:iam::aws:policy/SecurityAudit
        - arn:aws:iam::aws:policy/AmazonGuardDutyReadOnlyAccess
      InlinePolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: SecurityHubReadOnly
            Effect: Allow
            Action:
              - securityhub:Get*
              - securityhub:List*
              - securityhub:Describe*
              - securityhub:BatchGet*
            Resource: "*"
          - Sid: ConfigReadOnly
            Effect: Allow
            Action:
              - config:Get*
              - config:List*
              - config:Describe*
              - config:Select*
            Resource: "*"
          - Sid: CloudTrailReadOnly
            Effect: Allow
            Action:
              - cloudtrail:Get*
              - cloudtrail:List*
              - cloudtrail:Describe*
              - cloudtrail:LookupEvents
            Resource: "*"
      SessionDuration: !Ref AdminSessionDuration
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: ManagedBy
          Value: CloudFormation

  # Network admin - scoped to networking resources
  NetworkAdminPermissionSet:
    Type: AWS::SSO::PermissionSet
    Properties:
      Name: NetworkAdministrator
      Description: >
        Scoped access for network engineers managing VPCs, Transit Gateway,
        Route53, and related networking constructs.
      InstanceArn: !Ref SSOInstanceArn
      ManagedPolicies:
        - arn:aws:iam::aws:policy/job-function/NetworkAdministrator
      InlinePolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: TransitGatewayAdmin
            Effect: Allow
            Action:
              - ec2:*TransitGateway*
              - ec2:*VpnConnection*
              - ec2:*CustomerGateway*
              - ec2:*VpnGateway*
            Resource: "*"
      SessionDuration: !Ref AdminSessionDuration
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: ManagedBy
          Value: CloudFormation

  # Billing read-only for finance teams
  BillingReadOnlyPermissionSet:
    Type: AWS::SSO::PermissionSet
    Properties:
      Name: BillingReadOnly
      Description: Read-only billing and cost management access.
      InstanceArn: !Ref SSOInstanceArn
      ManagedPolicies:
        - arn:aws:iam::aws:policy/AWSBillingReadOnlyAccess
        - arn:aws:iam::aws:policy/job-function/Billing
      SessionDuration: !Ref ReadOnlySessionDuration
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: ManagedBy
          Value: CloudFormation

  # ─── ACCOUNT ASSIGNMENTS ──────────────────────────────────────────────────
  # NOTE: Group IDs must be retrieved from your Identity Store.
  # Use: aws identitystore list-groups --identity-store-id <id>
  # The assignments below use SSM Parameter Store to allow dynamic group IDs.

  # Platform admins → AdministratorAccess on Management Account
  PlatformAdminManagementAssignment:
    Type: AWS::SSO::Assignment
    Properties:
      InstanceArn: !Ref SSOInstanceArn
      PermissionSetArn: !GetAtt AdministratorAccessPermissionSet.PermissionSetArn
      PrincipalType: GROUP
      # Replace with the actual Group ID from your Identity Store
      PrincipalId: !Sub "{{resolve:ssm:/landing-zone/sso/group-id/platform-admins}}"
      TargetType: AWS_ACCOUNT
      TargetId: !Ref ManagementAccountId

  # Security team → SecurityAudit on Security Tooling Account
  SecurityTeamToolingAssignment:
    Type: AWS::SSO::Assignment
    Properties:
      InstanceArn: !Ref SSOInstanceArn
      PermissionSetArn: !GetAtt SecurityAuditPermissionSet.PermissionSetArn
      PrincipalType: GROUP
      PrincipalId: !Sub "{{resolve:ssm:/landing-zone/sso/group-id/security-team}}"
      TargetType: AWS_ACCOUNT
      TargetId: !Ref SecurityToolingAccountId

  # Security team → ReadOnly on Log Archive Account
  SecurityTeamLogArchiveAssignment:
    Type: AWS::SSO::Assignment
    Properties:
      InstanceArn: !Ref SSOInstanceArn
      PermissionSetArn: !GetAtt ReadOnlyAccessPermissionSet.PermissionSetArn
      PrincipalType: GROUP
      PrincipalId: !Sub "{{resolve:ssm:/landing-zone/sso/group-id/security-team}}"
      TargetType: AWS_ACCOUNT
      TargetId: !Ref LogArchiveAccountId

  # ─── SSO GROUP ID SSM PARAMETERS (placeholders) ───────────────────────────
  # Populate these with actual Group IDs from your Identity Store after
  # creating groups in IAM Identity Center or your IdP.

  PlatformAdminGroupIdParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /landing-zone/sso/group-id/platform-admins
      Type: String
      Value: "REPLACE_WITH_ACTUAL_GROUP_ID"
      Description: >
        Identity Store Group ID for Platform Administrators.
        Update this value after creating the group in IAM Identity Center.
      Tags:
        Environment: !Ref EnvironmentName
        ManagedBy: CloudFormation

  SecurityTeamGroupIdParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /landing-zone/sso/group-id/security-team
      Type: String
      Value: "REPLACE_WITH_ACTUAL_GROUP_ID"
      Description: >
        Identity Store Group ID for the Security Team.
        Update this value after creating the group in IAM Identity Center.
      Tags:
        Environment: !Ref EnvironmentName
        ManagedBy: CloudFormation

  # ─── SERVICE CONTROL POLICY GUARDRAIL IAM ROLE ────────────────────────────
  # Role for break-glass emergency access (bypass SSO if needed)
  BreakGlassRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${EnvironmentName}-break-glass-role"
      Description: Emergency break-glass access role. Use only when SSO is unavailable.
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${ManagementAccountId}:root"
            Action: sts:AssumeRole
            Condition:
              BoolIfExists:
                "aws:MultiFactorAuthPresent": true
      ManagedPolicies:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-break-glass-role"
        - Key: Sensitivity
          Value: CRITICAL
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  AdministratorPermissionSetArn:
    Description: ARN of the Administrator permission set
    Value: !GetAtt AdministratorAccessPermissionSet.PermissionSetArn
    Export:
      Name: !Sub "${EnvironmentName}-AdminPermissionSetArn"

  ReadOnlyPermissionSetArn:
    Description: ARN of the ReadOnly permission set
    Value: !GetAtt ReadOnlyAccessPermissionSet.PermissionSetArn
    Export:
      Name: !Sub "${EnvironmentName}-ReadOnlyPermissionSetArn"

  SecurityAuditPermissionSetArn:
    Description: ARN of the SecurityAudit permission set
    Value: !GetAtt SecurityAuditPermissionSet.PermissionSetArn
    Export:
      Name: !Sub "${EnvironmentName}-SecurityAuditPermissionSetArn"

  NetworkAdminPermissionSetArn:
    Description: ARN of the Network Administrator permission set
    Value: !GetAtt NetworkAdminPermissionSet.PermissionSetArn
    Export:
      Name: !Sub "${EnvironmentName}-NetworkAdminPermissionSetArn"

  BreakGlassRoleArn:
    Description: ARN of the break-glass emergency role
    Value: !GetAtt BreakGlassRole.Arn
    Export:
      Name: !Sub "${EnvironmentName}-BreakGlassRoleArn"
