AWSTemplateFormatVersion: "2010-09-09"
Description: >
  AWS Landing Zone - Security Baseline
  Enables and configures AWS GuardDuty, Security Hub, and AWS Config with
  CIS AWS Foundations Benchmark compliance rules. Deploy this stack in
  every account and region within the Organization.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "General"
        Parameters:
          - EnvironmentName
          - SecurityAccountId
          - LogArchiveBucketName
      - Label:
          default: "GuardDuty"
        Parameters:
          - GuardDutyFindingPublishFrequency
          - EnableS3Protection
          - EnableEKSProtection
          - EnableMalwareProtection
      - Label:
          default: "AWS Config"
        Parameters:
          - ConfigDeliveryFrequency
          - EnableConfigRecorder
      - Label:
          default: "Security Hub"
        Parameters:
          - EnableCISBenchmark
          - EnableAWSFoundationalBestPractices

Parameters:
  EnvironmentName:
    Type: String
    Default: landing-zone

  SecurityAccountId:
    Type: String
    Description: AWS Account ID of the Security Tooling (delegated admin) account.
    AllowedPattern: "^[0-9]{12}$"

  LogArchiveBucketName:
    Type: String
    Description: S3 bucket name in the Log Archive account for Config delivery.

  GuardDutyFindingPublishFrequency:
    Type: String
    Default: FIFTEEN_MINUTES
    AllowedValues:
      - FIFTEEN_MINUTES
      - ONE_HOUR
      - SIX_HOURS
    Description: How often GuardDuty publishes updated findings.

  EnableS3Protection:
    Type: String
    Default: "true"
    AllowedValues: ["true", "false"]
    Description: Enable GuardDuty S3 threat intelligence.

  EnableEKSProtection:
    Type: String
    Default: "true"
    AllowedValues: ["true", "false"]
    Description: Enable GuardDuty EKS audit log monitoring.

  EnableMalwareProtection:
    Type: String
    Default: "true"
    AllowedValues: ["true", "false"]
    Description: Enable GuardDuty malware scanning on EBS volumes.

  ConfigDeliveryFrequency:
    Type: String
    Default: TwentyFour_Hours
    AllowedValues:
      - One_Hour
      - Three_Hours
      - Six_Hours
      - Twelve_Hours
      - TwentyFour_Hours
    Description: How often AWS Config delivers a configuration snapshot.

  EnableConfigRecorder:
    Type: String
    Default: "true"
    AllowedValues: ["true", "false"]

  EnableCISBenchmark:
    Type: String
    Default: "true"
    AllowedValues: ["true", "false"]
    Description: Enable the CIS AWS Foundations Benchmark standard in Security Hub.

  EnableAWSFoundationalBestPractices:
    Type: String
    Default: "true"
    AllowedValues: ["true", "false"]
    Description: Enable the AWS Foundational Security Best Practices standard.

Conditions:
  IsConfigEnabled: !Equals [!Ref EnableConfigRecorder, "true"]
  EnableCIS: !Equals [!Ref EnableCISBenchmark, "true"]
  EnableAFSBP: !Equals [!Ref EnableAWSFoundationalBestPractices, "true"]

Resources:
  # ─── SNS TOPIC FOR SECURITY ALERTS ────────────────────────────────────────
  SecurityAlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${EnvironmentName}-security-alerts"
      DisplayName: Landing Zone Security Alerts
      KmsMasterKeyId: !Ref SecurityKMSKey
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: ManagedBy
          Value: CloudFormation

  SecurityAlertsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref SecurityAlertsTopic
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudWatchEvents
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sns:Publish
            Resource: !Ref SecurityAlertsTopic

  # ─── KMS KEY FOR ENCRYPTION AT REST ───────────────────────────────────────
  SecurityKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub "Landing Zone security services encryption key - ${EnvironmentName}"
      EnableKeyRotation: true
      MultiRegion: false
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: EnableRootAccess
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: kms:*
            Resource: "*"
          - Sid: AllowGuardDuty
            Effect: Allow
            Principal:
              Service: guardduty.amazonaws.com
            Action:
              - kms:GenerateDataKey
              - kms:Decrypt
            Resource: "*"
          - Sid: AllowCloudWatchLogs
            Effect: Allow
            Principal:
              Service: logs.amazonaws.com
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: "*"
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: ManagedBy
          Value: CloudFormation

  SecurityKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub "alias/${EnvironmentName}-security-key"
      TargetKeyId: !Ref SecurityKMSKey

  # ─── AMAZON GUARDDUTY ─────────────────────────────────────────────────────
  GuardDutyDetector:
    Type: AWS::GuardDuty::Detector
    Properties:
      Enable: true
      FindingPublishingFrequency: !Ref GuardDutyFindingPublishFrequency
      DataSources:
        S3Logs:
          Enable: !Equals [!Ref EnableS3Protection, "true"]
        Kubernetes:
          AuditLogs:
            Enable: !Equals [!Ref EnableEKSProtection, "true"]
        MalwareProtection:
          ScanEc2InstanceWithFindings:
            EbsVolumes: !Equals [!Ref EnableMalwareProtection, "true"]
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: ManagedBy
          Value: CloudFormation

  # CloudWatch Event Rule for HIGH/CRITICAL GuardDuty findings
  GuardDutyHighFindingsRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "${EnvironmentName}-guardduty-high-findings"
      Description: Alerts on HIGH and CRITICAL severity GuardDuty findings.
      State: ENABLED
      EventPattern:
        source:
          - aws.guardduty
        detail-type:
          - GuardDuty Finding
        detail:
          severity:
            - numeric:
                - ">="
                - 7
      Targets:
        - Id: SecurityAlertsSNS
          Arn: !Ref SecurityAlertsTopic
          InputTransformer:
            InputPathsMap:
              severity: "$.detail.severity"
              type: "$.detail.type"
              description: "$.detail.description"
              account: "$.detail.accountId"
              region: "$.detail.region"
            InputTemplate: |
              "GUARDDUTY ALERT | Severity: <severity> | Type: <type> | Account: <account> | Region: <region> | Description: <description>"

  # ─── AWS SECURITY HUB ─────────────────────────────────────────────────────
  SecurityHub:
    Type: AWS::SecurityHub::Hub
    DependsOn: GuardDutyDetector
    Properties:
      Tags:
        Environment: !Ref EnvironmentName
        ManagedBy: CloudFormation

  # CIS AWS Foundations Benchmark v1.4
  CISBenchmarkStandard:
    Type: AWS::SecurityHub::Standard
    Condition: EnableCIS
    DependsOn: SecurityHub
    Properties:
      StandardsArn: !Sub "arn:aws:securityhub:${AWS::Region}::standards/cis-aws-foundations-benchmark/v/1.4.0"

  # AWS Foundational Security Best Practices
  AWSFoundationalBPStandard:
    Type: AWS::SecurityHub::Standard
    Condition: EnableAFSBP
    DependsOn: SecurityHub
    Properties:
      StandardsArn: !Sub "arn:aws:securityhub:${AWS::Region}::standards/aws-foundational-security-best-practices/v/1.0.0"

  # EventBridge rule for CRITICAL Security Hub findings
  SecurityHubCriticalFindingsRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "${EnvironmentName}-securityhub-critical-findings"
      Description: Alerts on CRITICAL Security Hub findings.
      State: ENABLED
      EventPattern:
        source:
          - aws.securityhub
        detail-type:
          - Security Hub Findings - Imported
        detail:
          findings:
            Severity:
              Label:
                - CRITICAL
                - HIGH
      Targets:
        - Id: SecurityHubSNS
          Arn: !Ref SecurityAlertsTopic

  # ─── AWS CONFIG ───────────────────────────────────────────────────────────
  ConfigRecorderRole:
    Type: AWS::IAM::Role
    Condition: IsConfigEnabled
    Properties:
      RoleName: !Sub "${EnvironmentName}-config-recorder-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicies:
        - arn:aws:iam::aws:policy/service-role/AWS_ConfigRole
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

  ConfigRecorder:
    Type: AWS::Config::ConfigurationRecorder
    Condition: IsConfigEnabled
    Properties:
      Name: !Sub "${EnvironmentName}-config-recorder"
      RoleARN: !GetAtt ConfigRecorderRole.Arn
      RecordingGroup:
        AllSupported: true
        IncludeGlobalResourceTypes: true
        RecordingStrategy:
          UseOnly: ALL_SUPPORTED_RESOURCE_TYPES

  ConfigDeliveryChannel:
    Type: AWS::Config::DeliveryChannel
    Condition: IsConfigEnabled
    DependsOn: ConfigRecorder
    Properties:
      Name: !Sub "${EnvironmentName}-config-delivery"
      S3BucketName: !Ref LogArchiveBucketName
      S3KeyPrefix: !Sub "config/${AWS::AccountId}"
      ConfigSnapshotDeliveryProperties:
        DeliveryFrequency: !Ref ConfigDeliveryFrequency

  # ─── CONFIG RULES (CIS-aligned) ───────────────────────────────────────────

  # Ensure MFA is enabled on root account
  RootMFAEnabledRule:
    Type: AWS::Config::ConfigRule
    Condition: IsConfigEnabled
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: !Sub "${EnvironmentName}-root-mfa-enabled"
      Description: "CIS 1.1 - Ensure MFA is enabled for the root account."
      Source:
        Owner: AWS
        SourceIdentifier: ROOT_ACCOUNT_MFA_ENABLED

  # Ensure access keys are rotated within 90 days
  AccessKeyRotationRule:
    Type: AWS::Config::ConfigRule
    Condition: IsConfigEnabled
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: !Sub "${EnvironmentName}-access-key-rotation"
      Description: "CIS 1.4 - Ensure access keys are rotated every 90 days."
      Source:
        Owner: AWS
        SourceIdentifier: ACCESS_KEYS_ROTATED
      InputParameters:
        maxAccessKeyAge: "90"

  # Ensure no security groups allow unrestricted SSH
  RestrictedSSHRule:
    Type: AWS::Config::ConfigRule
    Condition: IsConfigEnabled
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: !Sub "${EnvironmentName}-restricted-ssh"
      Description: "CIS 4.1 - Ensure no security groups allow unrestricted SSH (port 22)."
      Source:
        Owner: AWS
        SourceIdentifier: INCOMING_SSH_DISABLED

  # Ensure no security groups allow unrestricted RDP
  RestrictedRDPRule:
    Type: AWS::Config::ConfigRule
    Condition: IsConfigEnabled
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: !Sub "${EnvironmentName}-restricted-rdp"
      Description: "CIS 4.2 - Ensure no security groups allow unrestricted RDP (port 3389)."
      Source:
        Owner: AWS
        SourceIdentifier: RESTRICTED_INCOMING_TRAFFIC
      InputParameters:
        blockedPort1: "3389"

  # Ensure CloudTrail is enabled
  CloudTrailEnabledRule:
    Type: AWS::Config::ConfigRule
    Condition: IsConfigEnabled
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: !Sub "${EnvironmentName}-cloudtrail-enabled"
      Description: "CIS 2.1 - Ensure CloudTrail is enabled in all regions."
      Source:
        Owner: AWS
        SourceIdentifier: MULTI_REGION_CLOUD_TRAIL_ENABLED

  # Ensure EBS volumes are encrypted
  EBSEncryptionRule:
    Type: AWS::Config::ConfigRule
    Condition: IsConfigEnabled
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: !Sub "${EnvironmentName}-ebs-encryption-enabled"
      Description: "Ensure new EBS volumes are encrypted by default."
      Source:
        Owner: AWS
        SourceIdentifier: EC2_EBS_ENCRYPTION_BY_DEFAULT

  # Ensure S3 buckets have server-side encryption enabled
  S3EncryptionRule:
    Type: AWS::Config::ConfigRule
    Condition: IsConfigEnabled
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: !Sub "${EnvironmentName}-s3-bucket-encryption"
      Description: "Ensure S3 buckets have server-side encryption enabled."
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_SERVER_SIDE_ENCRYPTION_ENABLED

  # Ensure S3 buckets block public access
  S3PublicAccessRule:
    Type: AWS::Config::ConfigRule
    Condition: IsConfigEnabled
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: !Sub "${EnvironmentName}-s3-block-public-access"
      Description: "Ensure S3 buckets block public access at the account level."
      Source:
        Owner: AWS
        SourceIdentifier: S3_ACCOUNT_LEVEL_PUBLIC_ACCESS_BLOCKS_PERIODIC

  # Ensure VPC Flow Logs are enabled
  VPCFlowLogsRule:
    Type: AWS::Config::ConfigRule
    Condition: IsConfigEnabled
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: !Sub "${EnvironmentName}-vpc-flow-logs-enabled"
      Description: "CIS 2.9 - Ensure VPC flow logging is enabled in all VPCs."
      Source:
        Owner: AWS
        SourceIdentifier: VPC_FLOW_LOGS_ENABLED

  # Ensure IMDSv2 is required on EC2 instances
  IMDSv2Rule:
    Type: AWS::Config::ConfigRule
    Condition: IsConfigEnabled
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: !Sub "${EnvironmentName}-imdsv2-required"
      Description: "Ensure EC2 instances require IMDSv2 (token-based metadata service)."
      Source:
        Owner: AWS
        SourceIdentifier: EC2_IMDSV2_CHECK

  # Ensure RDS instances are not publicly accessible
  RDSPublicAccessRule:
    Type: AWS::Config::ConfigRule
    Condition: IsConfigEnabled
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: !Sub "${EnvironmentName}-rds-no-public-access"
      Description: "Ensure RDS instances are not publicly accessible."
      Source:
        Owner: AWS
        SourceIdentifier: RDS_INSTANCE_PUBLIC_ACCESS_CHECK

  # Ensure IAM password policy meets CIS requirements
  IAMPasswordPolicyRule:
    Type: AWS::Config::ConfigRule
    Condition: IsConfigEnabled
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: !Sub "${EnvironmentName}-iam-password-policy"
      Description: "CIS 1.8-1.11 - Ensure IAM password policy meets complexity requirements."
      Source:
        Owner: AWS
        SourceIdentifier: IAM_PASSWORD_POLICY
      InputParameters:
        RequireUppercaseCharacters: "true"
        RequireLowercaseCharacters: "true"
        RequireSymbols: "true"
        RequireNumbers: "true"
        MinimumPasswordLength: "14"
        PasswordReusePrevention: "24"
        MaxPasswordAge: "90"

  # ─── CLOUDWATCH ALARMS (CIS-aligned) ──────────────────────────────────────
  UnauthorizedAPICallsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${EnvironmentName}-unauthorized-api-calls"
      AlarmDescription: "CIS 3.1 - Detect unauthorized API calls."
      MetricName: UnauthorizedAPICalls
      Namespace: LandingZoneMetrics
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref SecurityAlertsTopic

  ConsoleLoginWithoutMFAAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${EnvironmentName}-console-login-without-mfa"
      AlarmDescription: "CIS 3.2 - Detect console sign-in without MFA."
      MetricName: ConsoleLoginWithoutMFA
      Namespace: LandingZoneMetrics
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref SecurityAlertsTopic

  RootAccountUsageAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${EnvironmentName}-root-account-usage"
      AlarmDescription: "CIS 3.3 - Detect usage of the root account."
      MetricName: RootAccountUsage
      Namespace: LandingZoneMetrics
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref SecurityAlertsTopic

Outputs:
  GuardDutyDetectorId:
    Description: ID of the GuardDuty Detector
    Value: !Ref GuardDutyDetector
    Export:
      Name: !Sub "${EnvironmentName}-GuardDutyDetectorId"

  SecurityHubArn:
    Description: ARN of the Security Hub
    Value: !Sub "arn:aws:securityhub:${AWS::Region}:${AWS::AccountId}:hub/default"
    Export:
      Name: !Sub "${EnvironmentName}-SecurityHubArn"

  SecurityAlertsTopicArn:
    Description: ARN of the SNS topic for security alerts
    Value: !Ref SecurityAlertsTopic
    Export:
      Name: !Sub "${EnvironmentName}-SecurityAlertsTopicArn"

  SecurityKMSKeyArn:
    Description: ARN of the KMS key used by security services
    Value: !GetAtt SecurityKMSKey.Arn
    Export:
      Name: !Sub "${EnvironmentName}-SecurityKMSKeyArn"
